import connectDB from "@/lib/db";

import Product from "@/models/Product";

export async function GET(req) {
    await connectDB();
    const products = await Product.find();
    await Product.deleteMany();

    await Product.insertMany([
    {
        title: "Black Sneakers",
        description: "Stylish black sneakers for everyday wear.",
        price: 79.99,
        category: "Footwear",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Blue Denim Jacket",
        description: "Classic blue denim jacket for a casual look.",
        price: 59.99,
        category: "Apparel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Wireless Headphones",
        description: "High-quality wireless headphones with noise cancellation.",
        price: 129.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Smart Watch",
        description: "Modern smartwatch with fitness tracking and notifications.",
        price: 199.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Leather Backpack",
        description: "Durable leather backpack suitable for work and travel.",
        price: 89.99,
        category: "Accessories",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Cotton T-Shirt",
        description: "Comfortable and breathable cotton t-shirt for everyday use.",
        price: 24.99,
        category: "Apparel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Running Shoes",
        description: "Lightweight running shoes designed for comfort and performance.",
        price: 94.99,
        category: "Footwear",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Sunglasses",
        description: "Classic sunglasses with UV protection and a stylish frame.",
        price: 39.99,
        category: "Accessories",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Bluetooth Speaker",
        description: "Portable Bluetooth speaker with rich sound and long battery life.",
        price: 69.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Ceramic Coffee Mug",
        description: "Elegant ceramic coffee mug perfect for home or office.",
        price: 14.99,
        category: "Home",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Minimalist Wall Clock",
        description: "Modern minimalist wall clock designed for contemporary interiors.",
        price: 34.99,
        category: "Home",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Gaming Keyboard",
        description: "RGB mechanical gaming keyboard with responsive keys.",
        price: 89.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Wireless Mouse",
        description: "Ergonomic wireless mouse with precise tracking.",
        price: 29.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Hooded Sweatshirt",
        description: "Warm and comfortable hoodie perfect for casual outfits.",
        price: 49.99,
        category: "Apparel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Slim Fit Jeans",
        description: "Classic slim-fit jeans made with comfortable stretch denim.",
        price: 54.99,
        category: "Apparel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Canvas Sneakers",
        description: "Casual canvas sneakers with a lightweight and flexible design.",
        price: 44.99,
        category: "Footwear",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Travel Water Bottle",
        description: "Reusable stainless steel water bottle that keeps drinks cold.",
        price: 22.99,
        category: "Sports",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Yoga Mat",
        description: "Non-slip cushioned yoga mat suitable for workouts and stretching.",
        price: 32.99,
        category: "Sports",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Fitness Resistance Bands",
        description: "Set of resistance bands for strength training and home workouts.",
        price: 27.99,
        category: "Sports",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Desk Lamp",
        description: "Adjustable LED desk lamp with multiple brightness settings.",
        price: 42.99,
        category: "Home",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Laptop Stand",
        description: "Adjustable aluminum laptop stand for better desk ergonomics.",
        price: 39.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Portable Power Bank",
        description: "Compact power bank with fast charging capabilities.",
        price: 45.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Smartphone Tripod",
        description: "Flexible tripod for smartphones, photography, and video calls.",
        price: 25.99,
        category: "Accessories",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Leather Wallet",
        description: "Compact genuine leather wallet with multiple card slots.",
        price: 34.99,
        category: "Accessories",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Analog Wrist Watch",
        description: "Elegant analog wrist watch with a classic stainless steel design.",
        price: 79.99,
        category: "Accessories",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Baseball Cap",
        description: "Adjustable cotton baseball cap for a casual everyday style.",
        price: 19.99,
        category: "Accessories",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Winter Beanie",
        description: "Soft knitted beanie designed to keep you warm during winter.",
        price: 17.99,
        category: "Apparel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Classic Polo Shirt",
        description: "Versatile polo shirt made from soft and breathable fabric.",
        price: 39.99,
        category: "Apparel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Casual Chinos",
        description: "Comfortable chino pants suitable for casual and semi-formal outfits.",
        price: 49.99,
        category: "Apparel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Leather Belt",
        description: "Classic leather belt with a durable metal buckle.",
        price: 29.99,
        category: "Accessories",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Travel Duffel Bag",
        description: "Spacious duffel bag with multiple compartments for travel.",
        price: 64.99,
        category: "Travel",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Noise Cancelling Earbuds",
        description: "Compact wireless earbuds with active noise cancellation.",
        price: 109.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Tablet",
        description: "Portable tablet with a vibrant display for work and entertainment.",
        price: 249.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Mechanical Keyboard",
        description: "Premium mechanical keyboard designed for productivity and gaming.",
        price: 99.99,
        category: "Electronics",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Coffee Maker",
        description: "Compact coffee maker for brewing fresh coffee at home.",
        price: 74.99,
        category: "Home",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Electric Kettle",
        description: "Fast-boiling electric kettle with automatic shut-off.",
        price: 39.99,
        category: "Home",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Throw Pillow",
        description: "Soft decorative throw pillow to add comfort and style to your home.",
        price: 21.99,
        category: "Home",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Yoga Block Set",
        description: "Lightweight foam yoga blocks for improved balance and flexibility.",
        price: 18.99,
        category: "Sports",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Basketball",
        description: "Durable indoor and outdoor basketball with excellent grip.",
        price: 29.99,
        category: "Sports",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Camping Tent",
        description: "Lightweight two-person camping tent designed for outdoor adventures.",
        price: 119.99,
        category: "Outdoor",
        image: "https://picsum.photos/500/300",
    },
    {
        title: "Hiking Backpack",
        description: "Comfortable hiking backpack with multiple storage compartments.",
        price: 84.99,
        category: "Outdoor",
        image: "https://picsum.photos/500/300",
    }
]);

    return Response.json({ message: "Database seeded successfully!" });
}